# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            FPSAC / SFCA
tagline:          'Formal Power Series and Algebraic Combinatorics'
description:      'International conference series on Formal Power Series and Algebraic Combinatorics<br>Séries Formelles et Combinatoire Algébrique'
url:              http://fpsac.org
baseurl:          /

# About/contact
author:
  name:           'The FPSAC executive committee'
  url:            http://fpsac.org/
  email:          executive-office-fpsac@services.cnrs.fr

paginate:         5
paginate_path:       "/news/page:num/"

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/FPSAC/FPSAC.github.io
